### ISSUE TITLE
Delete slash command and button

### ISSUE THREAD

**Issue by CulturalProfessor** [RocketChat/Apps.Whiteboard#27]
Currently we don't have delete feature for whiteboards.

**Comment by lelamo2002** [comment]
Hi! I am looking for a project as part of an assignment of my Software Testing classes in university, in which I need to implement/improve an issue by using Test Driven Development. Do you reckon this would be a good issue?

**Comment by CulturalProfessor** [comment]
If just one issue then it will be a bit of overkill to setup and all,

**Comment by lelamo2002** [comment]
while waiting for a reply i ended setting it up already, so that's not a problem for me

**Comment by lelamo2002** [comment]
just so i can get it, it should have a delete button right here?

![image](https://github.com/RocketChat/Apps.Whiteboard/assets/56228340/d2e106f1-673f-478a-bf90-b74882f944e2)

and it should be able to be deleted writing something like `/whiteboard delete {whiteboardName}`?

**Comment by CulturalProfessor** [comment]
> just so i can get it, it should have a delete button right here?
> 
> ![image](https://github.com/RocketChat/Apps.Whiteboard/assets/56228340/d2e106f1-673f-478a-bf90-b74882f944e2)
> 
> and it should be able to be deleted writing something like `/whiteboard delete {whiteboardName}`?

Yeah that's the idea

**Comment by lelamo2002** [comment]
how do i join the channel?

**Comment by CulturalProfessor** [comment]
> how do i join the channel?

https://open.rocket.chat/channel/white-board-integration-team

**Comment by brf153** [comment]
@CulturalProfessor i think it is solved

**Comment by brf153** [comment]
Oh I thought it is same as delete board one..do we need to add a command like /whiteboard delete {boardid} to delete to delete the board? I can work on this issue if you want to

**Comment by Sumitwarrior7** [comment]
Delete board is already implemented, now the issue name should be changed to delete slash command only

**Comment by Sumitwarrior7** [comment]
please take a look on this pr and tell me for having any changes  : #46 
As delete slash command will be implemented just after this pr
@CulturalProfessor

**Comment by CulturalProfessor** [comment]
@Sumitwarrior7 implement the notification suggestion mentioned in channel

**Comment by Sumitwarrior7** [comment]
i am working on that already, but till now i am not able to crack it 
But if i crack it i will update the code for sure 

but creating a new message for notifying is also looking good, you can check it #46 and if you still dont fell good for it, i will remove it
@CulturalProfessor

**Comment by CulturalProfessor** [comment]
No I mean use send notification for sending that "user already exists" message, @brf153 also implemented it recently for list command.

**Comment by Sumitwarrior7** [comment]
ok implemented notification @CulturalProfessor 
please check : #46

**Comment by deepsingh245** [comment]
Is this issue resolved i would like to work on it.
