### ISSUE TITLE
List whiteboards slash command

### ISSUE THREAD

**Issue by CulturalProfessor** [RocketChat/Apps.Whiteboard#28]
A formatted list output for all the whiteboards created similar to **ls** command

**Comment by CulturalProfessor** [comment]
> Hey , @CulturalProfessor , can you please explain a bit about the issue a bit more , about what is to be done.

So we have to make a slashcommand to get the list of all whiteboards

**Comment by Mansikalra104** [comment]
ok 
Can u please this issue to me ?

**Comment by Sumitwarrior7** [comment]
Sorry to interrupt @Mansikalra104, But i am already working on this issue and this issue is majorly solved, so you can take other issue

**Comment by Mansikalra104** [comment]
No issues !

**Comment by brf153** [comment]
@CulturalProfessor I have fixed the issue

**Comment by brf153** [comment]
It is this fine? I am raising a pr for it.
