### ISSUE TITLE
Whiteboard naming bug

### ISSUE THREAD

**Issue by Sumitwarrior7** [RocketChat/Apps.Whiteboard#36]
When attempting to modify the name of a whiteboard using the settings button, there are instances where the name fails to update. 

For a clearer understanding of this issue, please refer to the attached video :

https://github.com/RocketChat/Apps.Whiteboard/assets/108853577/24035c23-b5fd-4043-a101-107446eeca44

**Comment by umangutkarsh** [comment]
Is this issue resolved?

**Comment by brf153** [comment]
@CulturalProfessor I think we should close this issue now. Also @Sumitwarrior7 please add `closes #{issue number}` to your PR to close the issue after fixing it with the PR.

**Comment by Sumitwarrior7** [comment]
closes  #37
