### ISSUE TITLE
Repo activity section in Readme

### ISSUE THREAD

**Issue by Sumitwarrior7** [RocketChat/Apps.Whiteboard#40]
Suggesting the addition of a "Repo Activity" section in the README.md to enhance the overall quality of the README file.

Not having permissions to directly modify the repository, so here are the steps to produce the Repo Activity section in readme file :-
1) Navigate to https://repobeats.axiom.co/
2) Sign in with the Github (Linked to the Rocket.chat/Apps.whiteboard repo) 
3) Got Manage Configs section or you can directly navigate to https://repobeats.axiom.co/configs
4) Add the owner and repo there and save it to generate the link for Repo Activity section
5) Copy the link and paste it to readme and commit, it will create the Repo Activity section in the readme

Sample Repo Activity image :  
![Screenshot from 2023-12-10 12-51-20](https://github.com/RocketChat/Apps.Whiteboard/assets/108853577/99869a5e-a3cf-4238-a96e-6cf6fdebb855)

**Comment by Sumitwarrior7** [comment]
Just proposing a little improvement in Readme.md file
@CulturalProfessor

**Comment by CulturalProfessor** [comment]
yeah it's cool we can include it @Sumitwarrior7

**Comment by OmkarDate29** [comment]
Can I work on this issue?
