### ISSUE TITLE
Multiple Whiteboards with same name 

### ISSUE THREAD

**Issue by Sumitwarrior7** [RocketChat/Apps.Whiteboard#44]
Users can currently create multiple whiteboards with the same name in a room, which isn't intended for the application

This behavior needs to be addressed and resolved to ensure the proper functioning of the application.

**Comment by Sumitwarrior7** [comment]
I am working on this issue @CulturalProfessor

**Comment by smitjiwani** [comment]
Instead of entering a different name. We could have modal to replace or numerically duplicate the whiteboard, i.e, if ```Untitled Whiteboard``` already exists the new board could replace the old board or create a new file called ```Untitled Whiteboard(1)```

**Comment by Sumitwarrior7** [comment]
For Untitled i.e., having no title, it is already there which you have dscribed
but for board having names this functionality is not desired, as the room will have unique wb names.

**Comment by smitjiwani** [comment]
Okay okay, so all the untitled wbs have a null value instead of a default untitled value, makes sense.👍👍
