### ISSUE TITLE
Feat: Add Gitpod Configuration for Apps.Whiteboard

### ISSUE THREAD

**Issue by brf153** [RocketChat/Apps.Whiteboard#48]
@CulturalProfessor I am working on this

**Comment by brf153** [comment]
@CulturalProfessor What all do we need to add in the gitpod config file?

**Comment by smitjiwani** [comment]
I have been working on gitpod with a whiteboard. As i understand you just have to setup the white white board once. and everytime rocket.chat core is is set up. whiteboard will work inside port 3000.

**Comment by CulturalProfessor** [comment]
@smitjiwani @brf153 add gitpod setup in readme also
