### ISSUE TITLE
/whiteboard create <whiteboard_name> command

### ISSUE THREAD

**Issue by Sumitwarrior7** [RocketChat/Apps.Whiteboard#49]
The existing "/whiteboard new" command lacks flexibility as it only generates whiteboards with Untitled name. 

Update the command to "/whiteboard create <whiteboard_name>", allowing users to name their whiteboards during creation. If no name is given, it defaults to creating an Untitled whiteboard

**Comment by Sumitwarrior7** [comment]
I am working on this @CulturalProfessor

**Comment by CulturalProfessor** [comment]
yeah cool go ahead on this
