### ISSUE TITLE
Change Board Name not working properly

### ISSUE THREAD

**Issue by brf153** [RocketChat/Apps.Whiteboard#63]
After changing the board name from Untitled Whiteboard, another board is being added to the persistance database rather than updating the previously rendered board.

https://github.com/RocketChat/Apps.Whiteboard/assets/107868772/173f8634-67aa-42c3-a3b3-35b534f3f4da

**Comment by brf153** [comment]
@CulturalProfessor this will fix the search whiteboard problem. We were adding boards rather than updating the previous one.

**Comment by Sumitwarrior7** [comment]
the issue you are talking about is related to changing names of board right?

can you just make a small video showing that on changing the name of the board , creates multiple whiteboard in mongodb database cuz when i was doing that it was not happening that multiple whiteboards are being created

**Comment by brf153** [comment]
@Sumitwarrior7 I was getting this when I was checking the database boards. You can see the logs.

![Screenshot from 2023-12-31 13-51-34](https://github.com/RocketChat/Apps.Whiteboard/assets/107868772/920201f6-cd12-41b7-9eb5-433f3d4a583e)

**Comment by brf153** [comment]
I actually saw this error when I was making the search command.

**Comment by brf153** [comment]
Nevermind I have fixed it. You can see the pr.

**Comment by Sumitwarrior7** [comment]
No problem if its an issue, but just cross verify it with whether this works correctly by seeing mongodb database

**Comment by Sumitwarrior7** [comment]
Just a suggestion, please check once the listboard command logic as well, because ig the issue is with that command logic maybe and I will also cross check, my command for renaming boards as well, and I will tell you about it asap
