### ISSUE TITLE
Board not rendering 

### ISSUE THREAD

**Issue by brf153** [RocketChat/Apps.Whiteboard#65]
![Screenshot from 2024-01-05 20-05-00](https://github.com/RocketChat/Apps.Whiteboard/assets/107868772/a1edbfa9-8b33-42bc-b010-eb874e5d9ec1)

I have recently setup my server again. THis time I have cloned the repo of Rocket.Chat and run the server using the command yarn dsv. I have deployed the whiteboard app in the server. Now, I am trying to make a new board using the command `/whiteboard new` but the board does not render.

**Comment by brf153** [comment]
@Sumitwarrior7 is `/whiteboard new` working?

**Comment by Sumitwarrior7** [comment]
It is working fine brother

**Comment by brf153** [comment]
oki there might be some issue in the latest server of rocket chat. version 6.6.0
